apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-demo-safra 
spec:
  selector:
    matchLabels:
      app: api-demo-safra
  template:
    metadata:
      labels:
        app: api-demo-safra
    spec:
      containers:
        - image: okteto.dev/java-gradle-api-demo-safra:1.0.0
          name: api-demo-safra

---

apiVersion: v1
kind: Service
metadata:
  name: api-demo-safra
spec:
  type: ClusterIP
  ports:
    - name: "api-demo-safra"
      port: 8080
  selector:
    app: api-demo-safra

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: api-demo-safra
  annotations:
    dev.okteto.com/generate-host: api-demo-safra
spec:
  rules:
    - http:
        paths:
          - backend:
              service:
                name: api-demo-safra
                port:
                  number: 8080
            path: /
            pathType: ImplementationSpecific